STATUS_STRIP_PX = 22
SASH_PX = 6

TIMELINE_BASE_DEFAULT_PX = 180

TOOLBAR_ICON_PX = 24
TOOLBAR_BUTTON_PAD = 4
TOOLBAR_LABEL_HEIGHT = 14
TOOLBAR_LABEL_SPACING = 2
TOOLBAR_EXTRA_MARGIN = 10

CARD_ROUNDING_PRIMARY = 6.0
CARD_ROUNDING_SECONDARY = 4.0
CARD_ROUNDING_INLINE = 3.0

CARD_PAD_PRIMARY = 8.0
CARD_PAD_SECONDARY = 6.0
CARD_PAD_INLINE = 4.0

CARD_ACCENT_WIDTH_PRIMARY = 4.0
